### ISSUE TITLE
can't find online docs

### ISSUE THREAD

**Issue by simi** [socketry/utopia#22]
docs linked at https://github.com/socketry/utopia#usage are not present anymore

**Comment by huba** [comment]
Not sure what happened to the live online documentation, for now the markdown files under
https://github.com/socketry/utopia/tree/master/documentation/pages/wiki should cover everything.

**Comment by ioquatix** [comment]
Fixed.

https://socketry.github.io/utopia/

**Comment by simi** [comment]
still not reachable here :(

**Comment by ioquatix** [comment]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/30030/79759224-85a64c00-8372-11ea-8889-e9154fd4fb35.png">

**Comment by simi** [comment]
probably DDS thingie, I'll check later

**Comment by ioquatix** [comment]
Okay please let me know!
